# Generated by Django 5.1.6 on 2025-03-03 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnilistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anilist_id', models.CharField(max_length=50)),
                ('anilist_username', models.CharField(max_length=255)),
                ('anilist_avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        )
    ]
