# Generated by Django 5.1.6 on 2025-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamgame',
            name='screenshots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
