# Generated by Django 5.1.6 on 2025-02-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_steamgame_screenshots'),
    ]

    operations = [
    ]
