# Generated by Django 5.1.6 on 2025-02-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_steamgame_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamgame',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='steamgame',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='steamgame',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
