# Generated by Django 5.1.6 on 2025-03-03 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_steamgame_genres_steamgame_release_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anilist_id', models.IntegerField(unique=True)),
                ('title_romaji', models.CharField(max_length=255)),
                ('title_english', models.CharField(blank=True, max_length=255, null=True)),
                ('title_native', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_image', models.URLField(max_length=500)),
                ('banner_image', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('WATCHING', 'En cours'), ('COMPLETED', 'Terminé'), ('PLANNING', 'Prévu'), ('DROPPED', 'Abandonné'), ('PAUSED', 'En pause')], max_length=20)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('average_score', models.IntegerField(blank=True, null=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ManyToManyField(related_name='anime_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
